add SplitSlice2Chunks utility function
armosec/utils-go pull request #1
Opened 2022-06-21 23:09 UTC by avrahams

2022-06-22 12:45 UTC, Bezbran requested changes

2022-06-22 12:45 UTC, Bezbran commented on httputils/httphelpers.go
> +func SplitSlice2Chunks[T any](slice []T, maxSize int, chunks chan<- []T, wg *sync.WaitGroup) {
add unitest

2022-06-22 12:45 UTC, Bezbran commented on go.mod
> +go 1.18
update GH actions

2022-06-23 11:25 UTC, avrahams commented on httputils/httphelpers.go
> +func SplitSlice2Chunks[T any](slice []T, maxSize int, chunks chan<- []T, wg *sync.WaitGroup) {
done

2022-06-23 11:25 UTC, avrahams commented on go.mod
> +go 1.18
done

2022-06-23 14:11 UTC, Bezbran approved these changes

2022-06-23 14:11 UTC, merged